name: "Action Invoker Workflow"

on:
  workflow_call:
    inputs:
      run_id:
        description: 'The workflow run ID to analyze'
        required: true
        type: string
      repo_owner:
        description: 'The owner of the repository'
        required: true
        type: string
      repo_name:
        description: 'The name of the repository'
        required: true
        type: string
    secrets:
      my_github_token:
        description: 'GitHub token'
        required: true
      custom_service_cookie:
        description: 'Custom Service Cookie'
        #required: true

jobs:
  collect-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the logs_summary_action Repository
        uses: actions/checkout@v2
        with:
          repository: shivendratiwari07/logs_summary_action  # Check out the correct repo
          ref: main  ## Ensure this is the correct branch

      - name: Invoke Custom Action
        uses: ./.github/actions  # This should point to the directory with your action.yml
        with:
          run_id: ${{ inputs.run_id }}
          repo_owner: ${{ inputs.repo_owner }}
          repo_name: ${{ inputs.repo_name }}
          github_token: ${{ secrets.my_github_token }}
          custom_service_cookie: ${{ secrets.CUSTOM_SERVICE_COOKIE_1 }}
        # env:
        #   CUSTOM_SERVICE_COOKIE: ${{ secrets.CUSTOM_SERVICE_COOKIE }} 



# name: "Action Invoker Workflow"

# on:
#   repository_dispatch:
#     types: [invoke-action]

# jobs:
#   invoke-action:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Invoke Custom Action
#         uses: ./.github/actions    # Change this to your actual action path or repository
#         with:
#           run_id: ${{ github.event.client_payload.run_id }}
#           repo_owner: ${{ github.event.client_payload.repo_owner }}
#           repo_name: ${{ github.event.client_payload.repo_name }}
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           CUSTOM_SERVICE_COOKIE: ${{ secrets.CUSTOM_SERVICE_COOKIE }}